version: "3.8"
services:
  app:
    build: .
    container_name: express
    user: "node"
    working_dir: /home/node/app
    environment:
        - NODE_ENV=development
    volumes:
        - ./:/home/node/app
        - /home/node/app/node_modules
        - /home/node/app/typings
    ports:
      - "80:3000"
    command: "npm start"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    container_name: mongo